schema_version: 1

context:
  name: parallel-numpy-rng
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 859f5ad437e4823c3ea769d8c31aec20c4def89a5a948ed0687821086ec11002

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2
    - numba

tests:
  - python:
      imports:
        - parallel_numpy_rng
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Parallel random number generation that produces the same result, regardless of the number of threads
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/lgarrison/parallel-numpy-rng/

extra:
  recipe-maintainers:
    - jan-janssen
